"""Minimal type stubs for httpx — enables Pysa sink resolution."""

from typing import Any

def get(url: str, **kwargs: Any) -> Any: ...
def post(url: str, data: Any = ..., **kwargs: Any) -> Any: ...
def put(url: str, data: Any = ..., **kwargs: Any) -> Any: ...
def patch(url: str, data: Any = ..., **kwargs: Any) -> Any: ...
