"""Minimal type stubs for requests — enables Pysa sink resolution."""

from typing import Any

class Response:
    status_code: int
    text: str
    content: bytes
    def json(self) -> Any: ...

def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, data: Any = ..., json: Any = ..., **kwargs: Any) -> Response: ...
def put(url: str, data: Any = ..., **kwargs: Any) -> Response: ...
def patch(url: str, data: Any = ..., **kwargs: Any) -> Response: ...
def delete(url: str, **kwargs: Any) -> Response: ...
