"""Minimal type stubs for keyring — enables Pysa sink resolution."""

def get_password(service_name: str, username: str) -> str | None: ...
def set_password(service_name: str, username: str, password: str) -> None: ...
